# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9871 sha256=7263f731799dd774192f618f20abde562758939a43ad70bc66c281f697a1a35f
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[10, 16, 14],
       [19, 11,  7],
       [20,  1,  3],
       [ 9, 18, 18],
       [10,  2, 17],
       [ 4, 15,  9],
       [16,  7,  8],
       [16, 12,  8],
       [ 6, 23, 18],
       [29, 22,  4],
       [ 5,  5, 29]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[28, 18, 14],
       [ 9,  1,  6],
       [21, 28, 27],
       [17, 30, 30],
       [22,  5, 18],
       [ 2,  9, 19],
       [ 9, 14,  5]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([13, 28, 26])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.geo(array1=ref_point, 
                              array2=np.random.randint(0, 31, size=(100000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

In [10]:
print('min azimuth', np.min(azi))
print('max azimuth', np.round(np.max(azi),2))

min azimuth 0.0
max azimuth 333.43


This is what we want to see!

In [11]:
geometry_class2 = geometry.geo(array1=np.array([0,   0,  0]), 
                               array2=np.array([[0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2],
                                                [-.2, 12, 12],
                                                [.2, 12, 12]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

array([  0.        ,  90.        , 180.        , 270.        ,
         0.        , 359.04515875,   0.95484125])

Testing the 45's for Charlie

In [12]:
geometry_class4 = geometry.geo(array1=np.array([0,   0,   0]), 
                               array2=np.array([[2,  2,   0],
                                                [4,  4,  -3],
                                                [12, 12,  2]]) )
# azimuth
azi4 = geometry_class4.calculate_azimuth()
azi4

array([45., 45., 45.])

## Using the junk drawer

In [13]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [14]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance   azimuth_cos  azimuth_sin  elevation_angle
0  43.312816 -5.547002e-01     0.832050       -28.991210
1  67.675697 -9.892035e-01    -0.146549       -30.585386
2  16.124515  6.123234e-17     1.000000         7.070555
3  12.000000  4.472136e-01     0.894427        33.690068
4  51.923020 -9.312428e-01     0.364399       -17.126603

In [15]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   41.175807    -0.550698     0.309796       -13.179020
std    20.099213     0.563330     0.619310        25.421129
min    12.000000    -0.989203    -0.501036       -39.413143
25%    29.718666    -0.946383    -0.210635       -29.788298
50%    46.086874    -0.865426     0.364399       -17.126603
75%    51.515375    -0.277350     0.863239        -4.913435
max    67.675697     0.447214     1.000000        33.690068

#### How expensive is the junk drawer?

In [16]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 10.6 ms, sys: 2.58 ms, total: 13.2 ms
Wall time: 12.4 ms
