# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9941 sha256=f103adc6c6a254741f2140324f6b9d427a8df7da8729b0cbc5dd07e49762905d
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[19,  4, 25],
       [ 8, 19, 20],
       [12, 13,  1],
       [ 3,  1, 14],
       [29,  8, 12],
       [11,  2, 20],
       [25, 24,  9],
       [21, 26,  4],
       [13, 24, 23],
       [28, 29, 21],
       [27,  3, 18]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[24, 11, 14],
       [27, 16, 24],
       [ 7, 13, 14],
       [24, 21, 29],
       [12, 14, 21],
       [17, 10,  8],
       [ 3, 13, 13]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([ 4, 13, 17])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.geo(array1=ref_point, 
                              array2=np.random.randint(0, 31, size=(1000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

In [10]:
print('max azimuth', np.max(azi))
print('min azimuth', np.min(azi))

max azimuth 359.927
min azimuth 0.0


This is what we want to see!

In [11]:
geometry_class2 = geometry.geo(array1=np.array([0,   0,  0]), 
                               array2=np.array([[0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

array([  0.,  90., 180., 270.,   0.])

## Using the junk drawer

In [12]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [13]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  40.644803    -0.999990     0.004451        -8.397376
1  48.456166    -0.506199     0.862417        16.115112
2   8.485281     0.986054     0.166425       -35.264390
3  49.315312     0.862726    -0.505672        25.950531
4  18.000000     0.989065     0.147481        23.962489

In [14]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   29.333532     0.159045    -0.170933        -7.282962
std    17.836326     0.818482     0.658145        29.584000
min     8.246211    -0.999990    -0.974652       -44.131749
25%    13.242641    -0.474134    -0.701327       -32.239871
50%    32.186954     0.223726     0.004451        -8.397376
75%    44.550484     0.924390     0.156953        20.038801
max    49.315312     0.989065     0.862417        25.950531

#### How expensive is the junk drawer?

In [15]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 19.1 ms, sys: 4.39 ms, total: 23.5 ms
Wall time: 23.3 ms
