# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=11632 sha256=cf50bc8409ee0e427e61646583fead5719dac8e6fcf62ffddb8cdeea6d065edd
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[ 4, 11, 24],
       [28, 21, 10],
       [23, 25, 12],
       [19, 19, 20],
       [12, 24, 30],
       [30, 16, 11],
       [ 9,  2, 22],
       [ 6, 19,  2],
       [27, 30,  2],
       [ 9, 18, 24],
       [15, 21, 19]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[ 0, 30,  0],
       [17, 16,  4],
       [17,  5, 18],
       [10, 25,  3],
       [ 8,  3, 17],
       [27,  2, 24],
       [ 0, 20, 26]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([15, 13, 17])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.GeoCalculator(ref_point, 
                              np.random.randint(0, 31, size=(1000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

Warning, Azimuth Calculation might be wrong for vertically offset points


In [10]:
print('min azimuth', np.min(azi))
print('max azimuth', np.round(np.max(azi),2))

min azimuth 0.0
max azimuth 356.42


This is what we want to see!

In [11]:
geometry_class2 = geometry.GeoCalculator(np.array([0,   0,  0]), 
                               np.array([[0,  0,  0],
                                                [0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2],
                                                [-.2, 12, 12],
                                                [.2, 12, 12]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

Warning, Azimuth Calculation might be wrong for vertically offset points


array([ 90.        ,   0.        ,  90.        , 180.        ,
       270.        ,   0.        , 359.04515875,   0.95484125])

Testing the 45's for Charlie

In [12]:
geometry_class4 = geometry.GeoCalculator(np.array([0,   0,   0]), 
                               np.array([[2,  2,   0],
                                                [4,  4,  -3],
                                                [12, 12,  2]]) )
# azimuth
azi4 = geometry_class4.calculate_azimuth()
azi4

array([45., 45., 45.])

## Using the junk drawer

In [14]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = geometry.GeoCalculator(ref_point, random_array4)


CPU times: user 1.43 ms, sys: 948 µs, total: 2.38 ms
Wall time: 1.44 ms


In [15]:
grid2 = yo4.get_geometry(ref_point, random_array4, pd_export=True)
grid2

Warning, Azimuth Calculation might be wrong for vertically offset points


distance   azimuth_cos  azimuth_sin  elevation_angle
0      15.297059 -9.701425e-01    -0.242536       -36.039893
1      21.283797  9.048187e-01    -0.425797       -28.023975
2      14.866069 -8.087361e-01    -0.588172        23.803656
3      15.684387  8.944272e-01    -0.447214         3.655525
4      18.165902 -5.812382e-01     0.813733       -61.735510
...          ...           ...          ...              ...
99995  21.213203 -6.000000e-01    -0.800000       -45.000000
99996  13.928388  6.123234e-17     1.000000        68.962489
99997  21.189620  9.734172e-01    -0.229039       -34.493658
99998  20.024984  9.980526e-01     0.062378       -36.816302
99999  16.431677  6.726728e-01     0.739940       -25.214384

[100000 rows x 4 columns]

In [16]:
grid2 = yo4.get_geometry(ref_point, random_array4, grid_resolution=3, pd_export=True)
grid2

Warning, Azimuth Calculation might be wrong for vertically offset points


distance   azimuth_cos  azimuth_sin  elevation_angle
0      45.891176 -9.701425e-01    -0.242536       -36.039893
1      63.851390  9.048187e-01    -0.425797       -28.023975
2      44.598206 -8.087361e-01    -0.588172        23.803656
3      47.053161  8.944272e-01    -0.447214         3.655525
4      54.497706 -5.812382e-01     0.813733       -61.735510
...          ...           ...          ...              ...
99995  63.639610 -6.000000e-01    -0.800000       -45.000000
99996  41.785165  6.123234e-17     1.000000        68.962489
99997  63.568860  9.734172e-01    -0.229039       -34.493658
99998  60.074953  9.980526e-01     0.062378       -36.816302
99999  49.295030  6.726728e-01     0.739940       -25.214384

[100000 rows x 4 columns]

In [17]:
grid4 = yo4.get_geometry(ref_point, random_array4, grid_resolution=False, pd_export=True)
grid4

Warning, Azimuth Calculation might be wrong for vertically offset points


distance   azimuth_cos  azimuth_sin  elevation_angle
0      15.297059 -9.701425e-01    -0.242536       -36.039893
1      21.283797  9.048187e-01    -0.425797       -28.023975
2      14.866069 -8.087361e-01    -0.588172        23.803656
3      15.684387  8.944272e-01    -0.447214         3.655525
4      18.165902 -5.812382e-01     0.813733       -61.735510
...          ...           ...          ...              ...
99995  21.213203 -6.000000e-01    -0.800000       -45.000000
99996  13.928388  6.123234e-17     1.000000        68.962489
99997  21.189620  9.734172e-01    -0.229039       -34.493658
99998  20.024984  9.980526e-01     0.062378       -36.816302
99999  16.431677  6.726728e-01     0.739940       -25.214384

[100000 rows x 4 columns]