# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9872 sha256=9730fb2628313f74459e883f8d62a1e7bebbf130682f2b727bfdca0449b16634
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[29,  3, 25],
       [25, 14, 24],
       [20,  2, 20],
       [ 4, 20, 22],
       [16, 28, 15],
       [15,  3, 20],
       [21, 23, 21],
       [ 1, 14,  7],
       [ 0,  1, 12],
       [26,  7,  2],
       [ 1, 11, 30]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[17, 26, 22],
       [12, 21, 18],
       [ 5, 23,  6],
       [13,  1,  6],
       [ 3,  0, 26],
       [28, 10, 17],
       [ 0, 26,  5]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([ 8, 25, 19])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.geo(array1=ref_point, 
                              array2=np.random.randint(0, 31, size=(100000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

In [10]:
print('min azimuth', np.min(azi))
print('max azimuth', np.round(np.max(azi),2))

min azimuth 0.0
max azimuth 348.69


This is what we want to see!

In [11]:
geometry_class2 = geometry.geo(array1=np.array([0,   0,  0]), 
                               array2=np.array([[0,  0,  0],
                                                [0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2],
                                                [-.2, 12, 12],
                                                [.2, 12, 12]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

array([ 90.        ,   0.        ,  90.        , 180.        ,
       270.        ,   0.        , 359.04515875,   0.95484125])

Testing the 45's for Charlie

In [12]:
geometry_class4 = geometry.geo(array1=np.array([0,   0,   0]), 
                               array2=np.array([[2,  2,   0],
                                                [4,  4,  -3],
                                                [12, 12,  2]]) )
# azimuth
azi4 = geometry_class4.calculate_azimuth()
azi4

array([45., 45., 45.])

## Using the junk drawer

In [13]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [14]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  19.078784     0.110432     0.993884        17.457603
1  11.489125    -0.707107     0.707107        -9.874961
2  26.981475    -0.554700    -0.832050       -43.938724
3  55.497748    -0.978980     0.203954       -25.102502
4  52.877216    -0.980581    -0.196116        14.829609

In [15]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   35.485012    -0.512415     0.097786       -13.157126
std    17.538993     0.461381     0.797690        24.717456
min    11.489125    -0.980581    -0.992278       -43.938724
25%    23.030130    -0.843044    -0.514083       -33.006996
50%    32.310989    -0.600000     0.203954        -9.874961
75%    51.518481    -0.222134     0.753553         5.135096
max    55.497748     0.124035     0.993884        17.457603

#### How expensive is the junk drawer?

In [16]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 11 ms, sys: 2.72 ms, total: 13.7 ms
Wall time: 12.9 ms
