# Small Notebook to double check functions

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9556 sha256=f341e372d2bc680bfc63ce74ce931a133360d7dade2fa108111e50c8f74bb536
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [5]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [6]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[20, 30, 19],
       [19,  1, 18],
       [19, 19,  4],
       [ 4, 17, 23],
       [28, 27, 10],
       [ 2,  8, 11],
       [26,  3, 16],
       [14, 16, 11],
       [ 9, 26,  7],
       [13, 16, 22],
       [15, 18, 13]])

In [7]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[14, 27, 14],
       [ 1,  7, 27],
       [ 0,  2,  5],
       [20,  7, 13],
       [ 6, 30, 13],
       [ 4,  5, 11],
       [24, 30, 14]])

In [8]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([ 8, 11, 29])

In [9]:
ref_point.shape

(3,)

In [10]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [11]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  22.737634     0.351123     0.936329        33.111342
1   8.306624    -0.868243    -0.496139        14.036243
2  26.851443    -0.664364    -0.747409        41.633539
3  20.396078     0.948683    -0.316228        38.659808
4  24.919872    -0.104685     0.994505        32.619243

In [12]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   21.659944    -0.035436     0.043417        32.980271
std     6.805976     0.700391     0.820033        10.062431
min     8.306624    -0.868243    -0.832050        14.036243
25%    19.893399    -0.609532    -0.621774        29.984559
50%    22.737634    -0.104685    -0.316228        33.111342
75%    25.885657     0.497630     0.850620        40.146674
max    29.017236     0.948683     0.994505        43.451842

In [13]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 14.8 ms, sys: 3.03 ms, total: 17.8 ms
Wall time: 16.5 ms
