# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=10007 sha256=637298b2ed9d4135dabf235766b9df6d5dede8651a5a1648a5ab2723159e31f7
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[14,  5, 14],
       [10, 19, 21],
       [15, 26,  3],
       [24, 30, 28],
       [ 2, 25, 22],
       [23, 16, 17],
       [30, 17, 21],
       [18, 26,  1],
       [23, 28, 12],
       [ 7,  8, 16],
       [ 9, 21, 19]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[12, 12, 10],
       [20, 19, 24],
       [10, 14,  3],
       [30, 23,  3],
       [12, 14, 21],
       [24, 30, 18],
       [17, 23, 21]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([11,  8,  2])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.geo(ref_point, 
                              np.random.randint(0, 31, size=(1000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

Warning, Azimuth Calculation might be wrong for vertically offset points


In [10]:
print('min azimuth', np.min(azi))
print('max azimuth', np.round(np.max(azi),2))

min azimuth 0.0
max azimuth 357.4


This is what we want to see!

In [11]:
geometry_class2 = geometry.geo(np.array([0,   0,  0]), 
                               np.array([[0,  0,  0],
                                                [0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2],
                                                [-.2, 12, 12],
                                                [.2, 12, 12]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

Warning, Azimuth Calculation might be wrong for vertically offset points


array([ 90.        ,   0.        ,  90.        , 180.        ,
       270.        ,   0.        , 359.04515875,   0.95484125])

Testing the 45's for Charlie

In [12]:
geometry_class4 = geometry.geo(np.array([0,   0,   0]), 
                               np.array([[2,  2,   0],
                                                [4,  4,  -3],
                                                [12, 12,  2]]) )
# azimuth
azi4 = geometry_class4.calculate_azimuth()
azi4

array([45., 45., 45.])

## Using the junk drawer

In [13]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [14]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  18.000000     0.970143     0.242536        41.633539
1  52.383203     0.773957     0.633238        40.029047
2  12.328828     0.986394    -0.164399         9.214335
3  48.456166     0.619644     0.784883         2.363508
4  39.899875     0.986394     0.164399        43.602909

In [15]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   40.178169     0.875134     0.362968        28.871269
std    18.184257     0.136835     0.317392        16.660106
min    12.328828     0.619644    -0.164399         2.363508
25%    28.949937     0.817442     0.203467        18.584312
50%    48.456166     0.928477     0.371391        37.301259
75%    51.131530     0.978268     0.570984        40.831293
max    60.299254     0.986394     0.784883        43.602909

#### How expensive is the junk drawer?

In [16]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

Warning, Azimuth Calculation might be wrong for vertically offset points
CPU times: user 17.9 ms, sys: 4.31 ms, total: 22.3 ms
Wall time: 20.3 ms
