# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9862 sha256=7a06449a122fb44630ce68fb4029e33a9c2bd6d88868689bd108d8950db67efd
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[12, 17,  9],
       [ 8,  1, 29],
       [17, 14,  6],
       [ 8, 22,  7],
       [ 0, 22, 20],
       [26, 22, 17],
       [29, 23, 16],
       [16,  9, 14],
       [19,  8, 20],
       [ 0,  5,  5],
       [ 7, 20, 26]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[22, 18, 23],
       [27, 10, 14],
       [10, 19, 27],
       [13,  0,  8],
       [13,  2, 19],
       [ 4, 15, 14],
       [ 1, 17, 12]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([ 0, 14, 24])

In [8]:
ref_point.shape

(3,)

## Testing Azimuth

In [9]:
geometry_class = geometry.geo(array1=ref_point, 
                              array2=np.random.randint(0, 31, size=(1000, 3)))
# azimuth
azi = geometry_class.calculate_azimuth()

In [10]:
print('max azimuth', np.max(azi))
print('min azimuth', np.min(azi))

max azimuth 358.02506598911805
min azimuth 0.0


This is what we want to see!

In [11]:
geometry_class2 = geometry.geo(array1=np.array([0,   0,  0]), 
                               array2=np.array([[0,  1,  0],
                                                [1,  0,  12],
                                                [0, -1,  3],
                                                [-1, 0, -3],
                                                [0,  7,  2]]) )
# azimuth
azi2 = geometry_class2.calculate_azimuth()

azi2

array([ 90.,   0., 270., 180.,  90.])

Testing the 45's for Charlie

In [12]:
geometry_class4 = geometry.geo(array1=np.array([0,   0,   0]), 
                               array2=np.array([[2,  2,   0],
                                                [4,  4,  -3],
                                                [12, 12,  2]]) )
# azimuth
azi4 = geometry_class4.calculate_azimuth()
azi4

array([45., 45., 45.])

## Using the junk drawer

In [13]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [14]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  44.766059     0.983870     0.178885        -2.558086
1  58.137767     0.989203    -0.146549       -18.983753
2  23.151674     0.894427     0.447214        14.529154
3  49.839743     0.680451    -0.732793       -32.702811
4  36.769553     0.734803    -0.678280       -15.214414

In [15]:
yo2.describe()

distance  azimuth_cos  azimuth_sin  elevation_angle
count   7.000000     7.000000     7.000000         7.000000
mean   37.016779     0.795589     0.037099       -20.245969
std    14.423977     0.244919     0.605491        21.513255
min    21.633308     0.316228    -0.732793       -44.038481
25%    23.985511     0.707627    -0.412414       -37.728102
50%    36.769553     0.894427     0.178885       -18.983753
75%    47.302901     0.977006     0.344875        -8.886250
max    58.137767     0.989203     0.948683        14.529154

#### How expensive is the junk drawer?

In [16]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 14.7 ms, sys: 3.99 ms, total: 18.7 ms
Wall time: 17.4 ms
