# Small Notebook to check geometery addition

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9766 sha256=e6b9df0d2c1d06bf126e4f48291d9efb8f1940aa0433636509eee30c8fb88c12
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry
from sealsml.function_drawer import add_geo

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(11, 3))
random_array

array([[29,  3,  0],
       [26, 13,  9],
       [ 2, 10, 20],
       [12,  7, 13],
       [29, 26,  4],
       [17,  2, 21],
       [20,  4, 11],
       [30, 12, 17],
       [13, 20, 17],
       [20,  2, 10],
       [23, 30,  5]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(7, 3))
random_array2

array([[ 2,  7, 11],
       [11, 28, 10],
       [ 1, 13, 18],
       [18,  9,  3],
       [ 4,  3, 18],
       [10, 20, 15],
       [16, 18, 29]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([10, 16, 26])

In [8]:
ref_point.shape

(3,)

In [9]:
yo = add_geo(ref_point, random_array, pd_export=False)
print('type:', type(yo))
print((np.shape(yo)))

type: <class 'numpy.ndarray'>
(11, 4)


In [10]:
yo2 = add_geo(ref_point, random_array2, pd_export=True)
print('type:', type(yo2))
yo2.head()

type: <class 'pandas.core.frame.DataFrame'>


distance  azimuth_cos  azimuth_sin  elevation_angle
0  19.235384    -0.664364    -0.747409        38.290163
1  20.024984     0.083045     0.996546        38.659808
2  12.409674    -0.948683    -0.316228        33.690068
3  25.337719     0.752577    -0.658505        42.614056
4  16.401219    -0.419058    -0.907959        26.565051

In [11]:
yo2.describe()

distance   azimuth_cos  azimuth_sin  elevation_angle
count   7.000000  7.000000e+00     7.000000         7.000000
mean   16.016240 -3.539998e-02    -0.045333        28.447286
std     6.142209  7.049214e-01     0.816023        23.444878
min     7.000000 -9.486833e-01    -0.907959       -23.198591
25%    12.057187 -5.417110e-01    -0.702957        30.127559
50%    16.401219  6.123234e-17    -0.316228        38.290163
75%    19.630184  4.178111e-01     0.656387        40.585128
max    25.337719  9.486833e-01     1.000000        42.614056

In [12]:
%%time

random_array4 = np.random.randint(0, 31, size=(100000, 3))
yo4 = add_geo(ref_point, random_array4, pd_export=True)

CPU times: user 16 ms, sys: 3.56 ms, total: 19.5 ms
Wall time: 18.1 ms
