# Small Notebook to double check functions

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=4130 sha256=0951814dfd36febd173dbd894fc9be350ff579f8d646cf71419b9ae02900af18
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [5]:
from sealsml.utils import distance_between_points_3d, calculate_azimuth, dip

## Data

Note the file:

In [6]:
ls

CONTRIBUTING.md         data/                   seals_ml.egg-info/
LICENSE                 dist/                   sealsml/
README.md               environment.yml         setup.py
ai2estemplate.egg-info/ githubcommand.md        tests/
build/                  notebooks/


In [7]:
file = 'data/FE_CBL2m_Ug5.4.nc'

In [8]:
ds = xr.open_dataset(file)
ds

<xarray.Dataset>
Dimensions:                (sourceDim: 8, locationDim: 3, z: 15, y: 30, x: 30,
                            time: 240)
Coordinates:
  * time                   (time) int64 0 1 2 3 4 5 ... 234 235 236 237 238 239
  * x                      (x) int64 0 1 2 3 4 5 6 7 ... 22 23 24 25 26 27 28 29
  * y                      (y) int64 0 1 2 3 4 5 6 7 ... 22 23 24 25 26 27 28 29
  * z                      (z) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * sourceDim              (sourceDim) int64 0 1 2 3 4 5 6 7
  * locationDim            (locationDim) int64 0 1 2
Data variables:
    srcAuxScLocation       (sourceDim, locationDim) float64 ...
    srcAuxScMassSpecValue  (sourceDim) float64 ...
    structureMask          (z, y, x) float64 ...
    xPos                   (z, y, x) float32 ...
    yPos                   (z, y, x) float32 ...
    zPos                   (z, y, x) float32 ...
    u                      (time, z, y, x) float32 ...
    v                      (time, z, y, x) float32 ...
    w                      (time, z, y, x) float32 ...
    q_CH4                  (time, z, y, x) float32 ...
Attributes:
    Original Filename:     FE_CBL2m_Ug5.4
    Fast Eddy Run:         Fast Eddy Run 1
    Time of Reformatting:  2023-09-11 08:34:26.197316

In [9]:
array = np.arange(0, 15, dtype=float).reshape(5, 3)

In [10]:
array2 = array + .75

In [11]:
array

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [12]:
array2[:,0] = array2[:,0]+.23

In [13]:

distance = distance_between_points_3d(array , array2)
distance

array([1.44409141, 1.44409141, 1.44409141, 1.44409141, 1.44409141])

## Azimuth

In [14]:
azi = calculate_azimuth(array, array2)
azi

array([346.47 ,   2.672,   6.905, 344.743,  22.637])

In [15]:
array3= np.array([0,0,3])
array4 = np.array([0,1,1])

In [16]:

azi = calculate_azimuth(array3, array4)
azi

0.0

## Dip

In [17]:
dip(array, array2)

array([27.51, 27.51, 27.51, 27.51, 27.51])

In [18]:
dip(array3, array4)

-41.76