# Small Notebook to double check functions

In [1]:
import xarray as xr
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
cd ..

/Users/thomasmartin/Documents/GitHub/seals-ml


In [3]:
!pip install .

Processing /Users/thomasmartin/Documents/GitHub/seals-ml
  Preparing metadata (setup.py) ... done
  Created wheel for ai2estemplate: filename=ai2estemplate-0.1.0-py3-none-any.whl size=9026 sha256=2084433d388641d0c379677edaca968306fbf8e09bc380e9b247d29a83134a80
  Stored in directory: /Users/thomasmartin/Library/Caches/pip/wheels/68/ad/03/c3c5488afa84764c8f4f104549404f63499d18391f0f22db83
Successfully built ai2estemplate
  Attempting uninstall: ai2estemplate
    Found existing installation: ai2estemplate 0.1.0
    Uninstalling ai2estemplate-0.1.0:
      Successfully uninstalled ai2estemplate-0.1.0


In [4]:
from sealsml import geometry

## Data

In [5]:
random_array = np.random.randint(0, 31, size=(5, 3))
random_array

array([[ 6,  3, 22],
       [12,  5, 16],
       [ 5, 28,  0],
       [ 1, 17,  9],
       [21, 11, 21]])

In [6]:
random_array2 = np.random.randint(0, 31, size=(5, 3))
random_array2

array([[17, 17,  6],
       [17, 20, 27],
       [10, 20, 30],
       [21, 26,  2],
       [24, 21, 24]])

In [7]:
ref_point = np.random.randint(0, 31, size=(3,))
ref_point 

array([ 6, 16, 17])

In [8]:
ref_point.shape

(3,)

In [9]:
geometry_class = geometry.geo(array1= random_array , array2=random_array2)
geometry_ref_point = geometry.geo(array1= ref_point  , array2=random_array2)

In [10]:
distance = geometry_class.distance_between_points_3d()
distance

array([23.93741841, 19.26136028, 31.44837039, 23.02172887, 10.86278049])

In [11]:
distance = geometry_ref_point.distance_between_points_3d()
distance

array([15.58845727, 15.39480432, 14.17744688, 23.4520788 , 19.94993734])

## Azimuth

In [12]:
azi = geometry_class.calculate_azimuth()
azi

array([ 51.84277341,  71.56505118, 302.00538321,  24.22774532,
        73.30075577])

In [13]:
azi = geometry_ref_point.calculate_azimuth()
azi

array([ 5.19442891, 19.98310652, 45.        , 33.69006753, 15.524111  ])

In [14]:
np.round(azi, 1)

array([ 5.2, 20. , 45. , 33.7, 15.5])

## Dip / Elevation Angle

In [15]:
ele_angle = geometry_class.calculate_elevation_angle()
ele_angle

array([-33.69006753,  30.06858282,  44.06080905, -16.92751306,
        15.2551187 ])

In [16]:
ele_angle = geometry_ref_point.calculate_elevation_angle()
ele_angle

array([ 34.50852299, -33.69006753, -42.8789036 ,  33.11134196,
       -19.29004622])